import { Component } from '@angular/core';

interface Category {
  PK_ID: number;
  CATEGORY_NAME: string;
}

interface PerformanceColumn {
  PK_ID: number;
  PERFORMANCE_METRIC_NAME: string;
  FK_CATEGORY: number;
}

interface Aircraft {
  PK_ID: number;
  aircraft_name: string;
}

interface AircraftPerformanceMetric {
  category_id: number;
  category_name: string;
  performance_column_id: number;
  performance_column_name: string;
  aircraft_id: number;
  aircraft_name: string;
  PERFORMANCE_VALUE: number;
}

@Component({
    selector: 'app-dashboard',
    templateUrl: './dashboard.component.html',
    styleUrl: './dashboard.component.css',
    standalone: false
})
export class DashboardComponent {
  categorias: Category[] = [
    { PK_ID: 1, CATEGORY_NAME: 'Weights' },
    { PK_ID: 2, CATEGORY_NAME: 'Taxi' },
    { PK_ID: 3, CATEGORY_NAME: 'Speeds' },
  ];

  data: PerformanceColumn[] = [
    { PK_ID: 1, PERFORMANCE_METRIC_NAME: 'M1', FK_CATEGORY: 1 },
    { PK_ID: 2, PERFORMANCE_METRIC_NAME: 'M2', FK_CATEGORY: 1 },
    { PK_ID: 3, PERFORMANCE_METRIC_NAME: 'M3', FK_CATEGORY: 1 },
    { PK_ID: 4, PERFORMANCE_METRIC_NAME: 'M4', FK_CATEGORY: 1 },
    { PK_ID: 5, PERFORMANCE_METRIC_NAME: 'M5', FK_CATEGORY: 1 },
    { PK_ID: 6, PERFORMANCE_METRIC_NAME: 'M6', FK_CATEGORY: 1 },
    { PK_ID: 7, PERFORMANCE_METRIC_NAME: 'Tx1', FK_CATEGORY: 2 },
    { PK_ID: 8, PERFORMANCE_METRIC_NAME: 'Tx2', FK_CATEGORY: 2 },
    { PK_ID: 9, PERFORMANCE_METRIC_NAME: 'Tx3', FK_CATEGORY: 2 },
    { PK_ID: 10, PERFORMANCE_METRIC_NAME: 'Tx4', FK_CATEGORY: 2 },
    { PK_ID: 11, PERFORMANCE_METRIC_NAME: 'PS1', FK_CATEGORY: 3 },
    { PK_ID: 12, PERFORMANCE_METRIC_NAME: 'PS2', FK_CATEGORY: 3 },
    { PK_ID: 13, PERFORMANCE_METRIC_NAME: 'PS3', FK_CATEGORY: 3 },
    { PK_ID: 14, PERFORMANCE_METRIC_NAME: 'PS4', FK_CATEGORY: 3 },
  ];

  aircraft: Aircraft[] = [
    { PK_ID: 1, aircraft_name: 'Boeing 747' },
    { PK_ID: 2, aircraft_name: 'Airbus A380' },
    { PK_ID: 3, aircraft_name: 'Concorde' },
    { PK_ID: 4, aircraft_name: 'Lockheed Martin F-22 Raptor' },
    { PK_ID: 5, aircraft_name: 'Boeing 747' },
    { PK_ID: 6, aircraft_name: 'Airbus A380' },
    { PK_ID: 7, aircraft_name: 'Concorde' },
    { PK_ID: 8, aircraft_name: 'Lockheed Martin F-22 Raptor' },
    { PK_ID: 9, aircraft_name: 'Boeing 747' },
    { PK_ID: 10, aircraft_name: 'Airbus A380' },
    { PK_ID: 11, aircraft_name: 'Concorde' },
    { PK_ID: 12, aircraft_name: 'Lockheed Martin F-22 Raptor' },
    { PK_ID: 13, aircraft_name: 'Airbus A380' },
    { PK_ID: 14, aircraft_name: 'Concorde' },
    { PK_ID: 15, aircraft_name: 'Lockheed Martin F-22 Raptor' },
    { PK_ID: 16, aircraft_name: 'Boeing 747' },
    { PK_ID: 17, aircraft_name: 'Airbus A380' },
    { PK_ID: 18, aircraft_name: 'Concorde' },
    { PK_ID: 20, aircraft_name: 'Lockheed Martin F-22 Raptor' },
  ];

  aircraft_performance = [
    {
      PK_ID: 1,
      fk_aircraft: 1,
      fk_performance_column: 1,
      PERFORMANCE_VALUE: 1000,
    },
    {
      PK_ID: 2,
      fk_aircraft: 1,
      fk_performance_column: 2,
      PERFORMANCE_VALUE: 1001,
    },
    {
      PK_ID: 3,
      fk_aircraft: 1,
      fk_performance_column: 3,
      PERFORMANCE_VALUE: 1002,
    },
    {
      PK_ID: 4,
      fk_aircraft: 1,
      fk_performance_column: 4,
      PERFORMANCE_VALUE: 1003,
    },
    {
      PK_ID: 5,
      fk_aircraft: 1,
      fk_performance_column: 5,
      PERFORMANCE_VALUE: 1004,
    },
    {
      PK_ID: 6,
      fk_aircraft: 1,
      fk_performance_column: 6,
      PERFORMANCE_VALUE: 1005,
    },
    {
      PK_ID: 7,
      fk_aircraft: 1,
      fk_performance_column: 7,
      PERFORMANCE_VALUE: 2000,
    },
    {
      PK_ID: 8,
      fk_aircraft: 1,
      fk_performance_column: 8,
      PERFORMANCE_VALUE: 2001,
    },
    {
      PK_ID: 9,
      fk_aircraft: 1,
      fk_performance_column: 9,
      PERFORMANCE_VALUE: 2002,
    },
    {
      PK_ID: 10,
      fk_aircraft: 1,
      fk_performance_column: 10,
      PERFORMANCE_VALUE: 2003,
    },
    {
      PK_ID: 11,
      fk_aircraft: 1,
      fk_performance_column: 11,
      PERFORMANCE_VALUE: 4000,
    },
    {
      PK_ID: 12,
      fk_aircraft: 1,
      fk_performance_column: 12,
      PERFORMANCE_VALUE: 4001,
    },
    {
      PK_ID: 13,
      fk_aircraft: 1,
      fk_performance_column: 13,
      PERFORMANCE_VALUE: 4002,
    },
    {
      PK_ID: 14,
      fk_aircraft: 1,
      fk_performance_column: 14,
      PERFORMANCE_VALUE: 4003,
    },
  ];

  aircraft_performance_metrics: AircraftPerformanceMetric[] = [
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1000 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1001 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1002 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1004 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 1005 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2000 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2001 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2002 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 2003 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4000 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4001 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4002 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 1, "aircraft_name": "Boeing 747", "PERFORMANCE_VALUE": 4003 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 1, "performance_column_name": "M1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1010 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 2, "performance_column_name": "M2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1011 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 3, "performance_column_name": "M3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1012 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 4, "performance_column_name": "M4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1013 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 5, "performance_column_name": "M5", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1014 },
    { "category_id": 1, "category_name": "Weights", "performance_column_id": 6, "performance_column_name": "M6", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 1015 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 7, "performance_column_name": "Tx1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2010 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 8, "performance_column_name": "Tx2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2011 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 9, "performance_column_name": "Tx3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2012 },
    { "category_id": 2, "category_name": "Taxi", "performance_column_id": 10, "performance_column_name": "Tx4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 2013 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 11, "performance_column_name": "PS1", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4010 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 12, "performance_column_name": "PS2", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4011 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 13, "performance_column_name": "PS3", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4012 },
    { "category_id": 3, "category_name": "Speeds", "performance_column_id": 14, "performance_column_name": "PS4", "aircraft_id": 2, "aircraft_name": "Airbus A380", "PERFORMANCE_VALUE": 4013 }
  ];

  getUniqueMetrics(categoryName: string): PerformanceColumn[] {
    return this.data.filter(metric => this.aircraft_performance_metrics.some(apm => apm.category_name === categoryName && apm.performance_column_name === metric.PERFORMANCE_METRIC_NAME));
  }

  getDataForMetricAndCategory(performance_column_id: number, categoryName: string): AircraftPerformanceMetric[] {
    return this.aircraft_performance_metrics.filter(apm => apm.performance_column_id === performance_column_id && apm.category_name === categoryName);
  }



  toggleCategory(category: string): void {
    this.expandedCategories[category] = !this.expandedCategories[category];
  }

  isCategoryExpanded(category: string): boolean {
    return this.expandedCategories[category];
  }

  expandedCategories: { [key: string]: boolean } = {
    Weights: true,
    Taxi: false,
    Speeds: false,
  };

  toggleAllCategories(event: any): void {
    const expand = event.checked;
    this.expandedCategories['Taxi'] = expand;
    this.expandedCategories['Speeds'] = expand;
  }

}